server:
  port: 8082
  servlet:
    context-path: /api/management
  error:
    include-message: always
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[default_schema]": shop
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
