server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
      - id: authModule
        uri: http://localhost:8081/
        predicates:
        - Path=/api/auth/**
      - id: managementModule
        uri: http://localhost:8082/
        predicates:
        - Path=/api/management/**
        filters:
        - ManagementFilter
      - id: mainModule
        uri: http://localhost:8083/
        predicates:
        - Path=/api/main/**
        filters:
        - MainFilter
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        "[default_schema]": shop
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver