CREATE TABLE "EPSR"."WEBCOMPSETTINGS" (
	"SETTINGKEY" VARCHAR (50) NOT NULL, 
	"SETTINGVAL" VARCHAR (100) NOT NULL, 
	"DESCRIPTION" VARCHAR (200), 
	"MODIFICATIONTIME" TIMESTAMP, 
	PRIMARY KEY ("SETTINGKEY") 
	)
;

CREATE TABLE "EPSR"."SITEPUBLISHPNP" (
	"TT" VARCHAR (15) NOT NULL, 
	"HLQ" VARCHAR (15) NOT NULL, 
	"MK" VARCHAR (15) NOT NULL, 
	"PN" VARCHAR (15) NOT NULL, 
	"EC" VARCHAR (24) NOT NULL, 
	"COMPID" VARCHAR (20) NOT NULL, 
	"TYPE" VARCHAR (20), 
	"SIZE" BIGINT, 
	"COMPRESSSIZE" BIGINT, 
	"DESCRIPTION" VARCHAR (256), 
	"CREATIONTIME" TIMESTAMP, 
	"MODIFICATIONTIME" TIMESTAMP, 
	"USERID" VARCHAR (64), 
	"PUBLISHSTATUS" INTEGER NOT NULL, 
	PRIMARY KEY (TT, HLQ, MK, PN, EC, COMPID),
	FOREIGN KEY ("COMPID") REFERENCES "EPSR"."EPSRSITE" ("COMPID") ON DELETE CASCADE ON UPDATE NO ACTION
	) 
	DATA CAPTURE NONE;

CREATE TABLE "EPSR"."SITEPUBLISHPKG" (
	"TT" VARCHAR (15) NOT NULL, 
	"HLQ" VARCHAR (15) NOT NULL, 
	"MK" VARCHAR (15) NOT NULL, 
	"PN" VARCHAR (15) NOT NULL, 
	"PKG" VARCHAR (20) NOT NULL, 
	"EC" VARCHAR (24) NOT NULL, 
	"COMPID" VARCHAR (20) NOT NULL, 
	"TYPE" VARCHAR (20), 
	"SIZE" BIGINT, 
	"COMPRESSSIZE" BIGINT, 
	"DESCRIPTION" VARCHAR (256), 
	"CREATIONTIME" TIMESTAMP, 
	"MODIFICATIONTIME" TIMESTAMP, 
	"USERID" VARCHAR (64), 
	"PUBLISHSTATUS" INTEGER NOT NULL, 
	PRIMARY KEY (TT, HLQ, MK, PN, PKG, EC, COMPID),
	FOREIGN KEY ("COMPID") REFERENCES "EPSR"."EPSRSITE" ("COMPID") ON DELETE CASCADE ON UPDATE NO ACTION
	) 
	DATA CAPTURE NONE;
	
ALTER TABLE "EPSR"."PNPACTION"
	ADD COLUMN "SITEID" VARCHAR (20);

ALTER TABLE "EPSR"."PKGACTION"
	ADD COLUMN "SITEID" VARCHAR (20);
	
ALTER TABLE "EPSR"."EPSRSITE"
	ADD COLUMN "AUTOPUBLISHENABLED" BOOLEAN;